ALTER DEFAULT PRIVILEGES FOR ROLE app_admin IN SCHEMA public
  REVOKE USAGE, SELECT ON SEQUENCES FROM app_public;

ALTER DEFAULT PRIVILEGES FOR ROLE app_admin IN SCHEMA public
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_public;

DROP TABLE IF EXISTS role_change_log;
DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS app_role;
